# Generated by Django 4.1.5 on 2023-01-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
