# Generated by Django 4.1.5 on 2023-01-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0002_time_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
