# Generated by Django 4.1.5 on 2023-01-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0003_campeonato_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='escudo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
